### ISSUE TITLE
カタログやスキーマが存在しない場合にテーブルリストを取得しようとする際のエラー

### ISSUE THREAD

**Issue by manabian-** [komae5519pv/komae_dbdemos#1]
カタログやスキーマが存在しない場合には、エラーとなってします。

![image](https://github.com/user-attachments/assets/8b9e3939-e759-46c6-85dc-fa4fdeff7729)

https://github.com/komae5519pv/komae_dbdemos/blob/18e2d3f7d3a6ec957b0069e71779eeeb8ba93435/pdcua_20241108/00-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB.ipynb#L64C1-L65C1

> [[SCHEMA_NOT_FOUND](https://docs.microsoft.com/azure/databricks/error-messages/error-classes#schema_not_found)] The schema `manabian` cannot be found. Verify the spelling and correctness of the schema and catalog.
If you did not qualify the name with a catalog, verify the current_schema() output, or qualify the name with the correct catalog.
To tolerate the error on drop use DROP SCHEMA IF EXISTS. SQLSTATE: 42704

![image](https://github.com/user-attachments/assets/587e31e2-6980-4f31-92e8-02dc7626cbfe)

**Comment by manabian-** [comment]
暫定対応としては、 存在しているスキーマである default の利用を案内しました。

**Comment by komae5519pv** [comment]
必須処理ではないためコメントアウトしました
