### ISSUE TITLE
カタログ作成権限がないユーザーがカタログを作成しようとするエラー

### ISSUE THREAD

**Issue by manabian-** [komae5519pv/komae_dbdemos#2]
カタログ作成権限がないユーザーがカタログを作成しようとするエラーとなってしまうようです。

![image](https://github.com/user-attachments/assets/3e965bd8-deb6-4ce5-a8f3-768c89ad394e)

https://github.com/komae5519pv/komae_dbdemos/blob/18e2d3f7d3a6ec957b0069e71779eeeb8ba93435/pdcua_20241108/00-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB.ipynb#L95C1-L96C1

> Py4JJavaError: An error occurred while calling o387.sql.
: com.databricks.sql.managedcatalog.acl.UnauthorizedAccessException: PERMISSION_DENIED: User does not have CREATE CATALOG on Metastore 'pcdua-shared-metastore-japaneast'.

![image](https://github.com/user-attachments/assets/1a94c0f9-b5aa-47b1-b52b-a834b459f897)

**Comment by manabian-** [comment]
暫定対応としては、カタログを作成するコードをコメントアウトしました。

**Comment by komae5519pv** [comment]
同様の対応を行いました
