### ISSUE TITLE
NOT NULL 制約がないテーブルに対して主キー制約を設定する際のエラー

### ISSUE THREAD

**Issue by manabian-** [komae5519pv/komae_dbdemos#3]
NOT NULL 制約がないテーブルに対して主キー制約を設定する際のエラーが発生します。cell 22 （trainにNULL拒否制約を追加）と cell 21（trainにPK設定追加） を入れ替える必要がありそうです。

https://github.com/komae5519pv/komae_dbdemos/blob/18e2d3f7d3a6ec957b0069e71779eeeb8ba93435/pdcua_20241108/00-%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB.ipynb#L823C1-L825C1

![image](https://github.com/user-attachments/assets/f221457d-eb64-4e96-9b8e-3f83cf094993)

> PrimaryKeyColumnsNullableException: Cannot create the primary key `pk_train_building_id` because its child column(s) `building_id` is nullable. Please change the column nullability and retry.

cell 22 実行後に、 cell 21 のコードを実行すると正常終了します。

![image](https://github.com/user-attachments/assets/2eda4ba8-e368-47e2-bb60-b9e287ee2528)

**Comment by manabian-** [comment]
暫定対応として、22 実行後に 21 を実行するように案内しました。

**Comment by komae5519pv** [comment]
同様の対応を行いました
